### ISSUE TITLE
Author URL

### ISSUE THREAD

**Issue by ghost** [REEA-Digital-Limited/Blogsters#1]
Hello,

Thanks a lot for the exstension. It would be nice to add a URL to the author avatar image. At least it can be redirected to the author page. 

https://ekerlabs.com/powercontent ⤵
It can inspire you. For J3 version only. J4 developer doesn't do it anymore.

Best Regards

**Comment by shaon-bahadur** [comment]
We appreciate your advice and will work to keep this functionality in the upcoming release.
